# Non-existing endpoint
GET http://localhost:7070/api/auth/test
###
POST http://localhost:7070/api/auth/register

{
    "username": "admin",
    "password": "test123"
}
###
POST http://localhost:7070/api/auth/login

{
    "username": "admin",
    "password": "test123"
}
> {%
    client.global.set("token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
    client.log("Username: " + response.body.username);
%}
###
GET http://localhost:7070/api/protected/user_demo
Authorization: Bearer {{token}}
###
GET http://localhost:7070/api/protected/admin_demo
Authorization: Bearer {{token}}
###
GET http://localhost:7070/api/routes
Authorization: Bearer {{token}}
###
GET http://localhost:7070/api/auth/verify
Authorization: Bearer {{token}}
###
GET http://localhost:7070/api/auth/tokenlifespan
Authorization: Bearer {{token}}