GET localhost:7070/api/routes

###
GET localhost:7070/api/hotel

###
GET localhost:7070/api/hotel/3

###
POST localhost:7070/api/hotel
Content-Type: "application/json"

{
    "name": "Park Hotel",
    "address": "Brorsonsvej 2",
    "rooms":[
        {
            "roomNumber": 101,
            "price": 1000
        }
    ]
}

###
PUT localhost:7070/api/hotel/1
Content-Type: "application/json"

{
    "name": "Lucky Star Hotel",
    "address": "Brorsonsvej 1"
}

###
DELETE localhost:7070/api/hotel/1

###
GET localhost:7070/api/hotel/1/rooms