GET localhost:7070/api/movies/search-open
Content-Type: "application/json"

{
    "text": "dru"
}

###
GET localhost:7070/api/movies/search
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "text": "olsen-banden"
}

###
GET localhost:7070/api/movies/recommendations
Authorization: Bearer {{token}}

###
GET localhost:7070/api/movies
Authorization: Bearer {{token}}

###
PUT localhost:7070/api/movies/580175
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT localhost:7070/api/movies/11389
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT localhost:7070/api/movies/1426674
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}


###
DELETE localhost:7070/api/movies/1078249
Authorization: Bearer {{token}}