PUT localhost:7070/api/movie/movie-search
Content-Type: "application/json"

{
    "text": "evi"
}

###
POST localhost:7070/api/movie/movie-rating/2
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT localhost:7070/api/movie/movie-rating/663870
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}

###
DELETE localhost:7070/api/movie/movie-rating/663870
Authorization: Bearer {{token}}

###
GET localhost:7070/api/movie/test