PUT localhost:7070/api/movie/movie-search
Content-Type: "application/json"

{
    "text": "evi"
}


###
PUT localhost:7070/api/movie/movie-rating/1078249
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}

###
DELETE localhost:7070/api/movie/movie-rating/663870
Authorization: Bearer {{token}}

###
GET localhost:7070/api/movie/movie-rating
Authorization: Bearer {{token}}