### Search without token
GET {{url}}/movies/search?title=intercepfin

### Search with token
GET {{url}}/movies/search?title=goblets
Authorization: Bearer {{token}}

###
GET {{url}}/movies/top100
Authorization: Bearer {{token}}

###
GET {{url}}/movies/recommendations
Authorization: Bearer {{token}}

###
GET {{url}}/movies/ratings
Authorization: Bearer {{token}}

###
GET {{url}}/movies/19995

###
PUT {{url}}/movies/299536/ratings
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT {{url}}/movies/12231/ratings
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}

###
DELETE {{url}}/movies/488/ratings
Authorization: Bearer {{token}}

###
GET {{url}}/movies/person/287

###
GET {{url}}/movies/collection/263

###
POST {{url}}/movies/update
Authorization: Bearer {{token}}