GET {{url}}/movies/search-open?text=avatar

###
GET {{url}}/movies/search?text=inception
Authorization: Bearer {{token}}

###
GET {{url}}/movies/recommendations
Authorization: Bearer {{token}}

###
GET {{url}}/movies
Authorization: Bearer {{token}}

###
GET {{url}}/movies/19995

###
PUT {{url}}/movies/299536
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}

###
PUT {{url}}/movies/12231
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}

###
PUT {{url}}/movies/1426674
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}


###
DELETE {{url}}/movies/155
Authorization: Bearer {{token}}

###
GET {{url}}/movies/person/488

###
GET {{url}}/movies/collection/10

###
POST {{url}}/movies/update
Authorization: Bearer {{token}}