# Non-existing endpoint
GET {{url}}/auth/test
###
POST {{url}}/auth/register

{
    "username": "testuser2",
    "password": "test123"
}
###
POST {{url}}/auth/login

{
    "username": "testuser1",
    "password": "test123"
}
> {%
    client.global.set("token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
    client.log("Username: " + response.body.username);
%}
###
GET {{url}}/protected/user_demo
Authorization: Bearer {{token}}
###
GET {{url}}/protected/admin_demo
Authorization: Bearer {{token}}
###
GET {{url}}/routes
Authorization: Bearer {{token}}
###
GET {{url}}/auth/verify
Authorization: Bearer {{token}}
###
GET {{url}}/auth/tokenlifespan
Authorization: Bearer {{token}}