GET {{url}}/movies/search-open
Content-Type: "application/json"

{
    "text": "dru"
}

###
GET {{url}}/movies/search
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "text": "olsen-banden"
}

###
GET {{url}}/movies/recommendations
Authorization: Bearer {{token}}

###
GET {{url}}/movies
Authorization: Bearer {{token}}

###
PUT {{url}}/movies/580175
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT {{url}}/movies/11389
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": true
}

###
PUT {{url}}/movies/1426674
Authorization: Bearer {{token}}
Content-Type: "application/json"

{
    "rating": false
}


###
DELETE {{url}}/api/movies/1078249
Authorization: Bearer {{token}}