# Non-existing endpoint
GET {{url}}/auth/test

###
POST {{url}}/auth/register

{
    "username": "testuser2",
    "password": "password2"
}

###
POST {{url}}/auth/login

{
    "username": "testuser3",
    "password": "password3"
}
> {%
    client.global.set("token", response.body.token);
    client.log("Logging Bearer Token.");
    client.log("Bearer " + response.body.token);
    client.log("Username: " + response.body.username);
%}

###
GET {{url}}/roles-test/anyone

###
GET {{url}}/roles-test/user
Authorization: Bearer {{token}}

###
GET {{url}}/roles-test/admin
Authorization: Bearer {{token}}

###
GET {{url}}/routes
Authorization: Bearer {{token}}

###
GET {{url}}/auth/verify
Authorization: Bearer {{token}}

###
GET {{url}}/auth/tokenlifespan
Authorization: Bearer {{token}}