@startuml
object Account {
    +String email
    +String hashedPassword
    +Role role
}

object Collection {
    +String name
}

object Credit {
    +String department
    +String job
    +String character
    +Integer rankInMovie
}

object Genre {
    +String name
}

object Movie {
    +String title
    +String originalTitle
    +Boolean adult
    +Boolean video
    +String originalLanguage
    +Double voteAverage
    +Integer voteCount
    +Double popularity
    +LocalDate releaseDate
    +String backdropPath
    +String posterPath
    +Integer runtime
    +String tagline
    +String status
    +String overview
    +OffsetDateTime lastTmdbSync
}

object MovieGenre {
    +Integer rankInMovie
}

object Person {
    +String name
}

object Rating {
    +Boolean rating
}

Account "1" -- "*" Rating
Movie "1" -- "*" Rating
Movie "1" -- "*" Credit
Person "1" -- "*" Credit
Movie "1" -- "*" MovieGenre
Genre "1" -- "*" MovieGenre
Movie "*" -- "0..1" Collection

@enduml
